# Server Configuration
server.port=8082
spring.application.name=frontrest

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=product-events-group

# Logging
logging.level.org.springframework.kafka=INFO
logging.level.com.example.events=DEBUG
logging.level.com.example.frontrest=DEBUG